### ISSUE TITLE
Fails to Run on MACOs

### ISSUE THREAD

**Issue by wherkamp** [kakaragame/Kakara#22]
Basically the Engine Test wont start on MacOS. 

```[LWJGL] Failed to load a library. Possible solutions:
    a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
    b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib
    at org.lwjgl.system.Library.loadSystem(Library.java:162)
    at org.lwjgl.system.Library.loadSystem(Library.java:62)
    at org.lwjgl.system.Library.<clinit>(Library.java:50)
    at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
    at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
    at org.lwjgl.system.Callback.<clinit>(Callback.java:41)
    at org.kakara.engine.gui.Window.init(Window.java:54)
    at org.kakara.engine.GameEngine.init(GameEngine.java:51)
    at org.kakara.engine.GameEngine.run(GameEngine.java:42)
    at org.kakara.engine.test.Main.main(Main.java:15)

Process finished with exit code 1```

**Comment by ryandw11** [comment]
Was this compiled onto a jar file or ran in intellij?

**Comment by wherkamp** [comment]
Intellij.
